# Generated by Django 4.2.3 on 2024-09-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_avater_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
